### ISSUE TITLE
Private notes

### ISSUE THREAD

**Issue by bmann** [Cobuilding/cobuilding.ca#3]
What do we want to do about private notes?

@jsayles suggested that we might just have another repo. In fact, a private repo with a (private) Github wiki might just work.

**Comment by jsayles** [comment]
A private repo is where my brain went first but I'm open to other suggestions.  A few important points I want to make when thinking through a solution.  Generally I want things to be as open as possible.  I want to highly discourage private conversations because they limit serendipitous idea collisions and are usually not required.  

One exception that does need to be kept private is information on people interested in this that have not yet agreed to be a part of it.  Example:  Today we talked with Amy Fox and she did agree to join the project.  Before that she was a person of interest and we need a way to share information and talk about people of interest without publishing their information on the website.

**Comment by bmann** [comment]
Ok.

So I think a private “notes” repo and using the wiki — and, for that matter, private issue queue — could work in the short term. 

But also: we could just use a shared Google folder and GDocs, which would be accessible to non coding nerds. 

I’m fine either way.

**Comment by jsayles** [comment]
It was decided that GDocs are a necessary evil and we going with that.
